const ENV_VARIABLES = [
  "NODE_ENV",
  "PORT",
  "SESSION_SECRET",
  "JWT_KEY",
  "JWT_REFRESH_KEY",
  "DATABASE_URL",
  "ASSEMBLY_API_KEY",
  "RAPID_API_KEY",
  "AWS_CLOUDFRONT_URL",
  "VIDEO_PROCESSOR_ENDPOINT",
  "VIDEO_PROCESSOR_ACCESS_KEY",
];
const NODE_ENV_OPTIONS = ["development", "production", "testing"];

export { ENV_VARIABLES, NODE_ENV_OPTIONS };
